### ISSUE TITLE
Should I check if I got multiple records of token query?

### ISSUE THREAD

**Issue by jameshwc** [jameshwc/java-backend-home-project#1]
https://github.com/jameshwc/java-backend-home-project/blob/63cd53a8d233a0d4fcc73285fb66dd35ad731e07/src/main/java/com/test/bank/service/AdminService.java#L47

As title, it's abnormal to get multiple records when querying of token. However, there's still a chance that some error happens. In that case, what should I do? Pass or fail to authenticate?

**Comment by kenchiang1211** [comment]
The token is inserted manually. so I assume there's only 1 possible record. But you point out a good question. The `Token` table schema better to create a composite unique index (AdminId, Token). So that we can avoid the question you mentioned.
