### ISSUE TITLE
What if the from-user doesn't have that much money?

### ISSUE THREAD

**Issue by jameshwc** [jameshwc/java-backend-home-project#2]
https://github.com/jameshwc/java-backend-home-project/blob/63cd53a8d233a0d4fcc73285fb66dd35ad731e07/src/main/java/com/test/bank/service/TransactionService.java#L39

What if the from-user doesn't have the amount of money as requested to transfer? Should I still return the TransferResponse as usual or return null to indicate that there's something wrong?

**Comment by jameshwc** [comment]
Also, what should I do when the transfer amount is negative?

**Comment by kenchiang1211** [comment]
Hi @jameshwc, if there's not sufficient money in from user's wallet. It should be looked as an invalid operation. I haven't defined this properly. I Will update in the future. Thank your feedback.
